# Generated by Django 3.0.8 on 2020-08-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='category',
            field=models.CharField(choices=[('AC-SEATER', 'AC-SEATER'), ('NON-AC-SEATER', 'NON-AC-SEATER'), ('AC-SLEEPER', 'AC-SLEEPER'), ('NON-AC-SLEEPER', 'NON-AC-SLEEPER')], max_length=15),
        ),
    ]
