# Generated by Django 3.0.8 on 2020-08-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_search_user_l'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_l',
        ),
    ]
