# Generated by Django 3.0.8 on 2020-08-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
