# Generated by Django 3.0.8 on 2020-08-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='user',
            new_name='us',
        ),
        migrations.AlterField(
            model_name='search',
            name='us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fun'),
        ),
    ]
