# Generated by Django 3.0.8 on 2020-08-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200808_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='us',
        ),
    ]
