# Generated by Django 3.0.8 on 2020-08-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='noofseats',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fun'),
        ),
    ]
