# Generated by Django 3.0.8 on 2020-08-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200809_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businfo',
            name='fromplace',
        ),
        migrations.RemoveField(
            model_name='businfo',
            name='toplace',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fun'),
        ),
    ]
