# Generated by Django 3.0.8 on 2020-08-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200809_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusInfo',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fun'),
        ),
    ]
