# Generated by Django 3.0.8 on 2020-08-09 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200809_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('depart', models.CharField(max_length=10)),
                ('fare', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fun'),
        ),
    ]
