# Generated by Django 3.0.8 on 2020-08-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200809_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
