# Generated by Django 3.0.8 on 2020-08-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BusInfo')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Search')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fun')),
            ],
        ),
    ]
