# Generated by Django 3.1 on 2020-08-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='businfo',
            name='av_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
