# Generated by Django 3.1 on 2020-08-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_businfo_av_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='place',
        ),
        migrations.AddField(
            model_name='bookings',
            name='fro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='to',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
