# Generated by Django 3.1 on 2020-08-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200812_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
