# Generated by Django 3.1 on 2020-08-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_bookings_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='date',
        ),
    ]
