# Generated by Django 3.1 on 2020-08-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_bookings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='dat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
